In [1]:
li=[2,3,4,5,6,7]
print(li)
type(li)


[2, 3, 4, 5, 6, 7]


list

In [6]:
import numpy as np 
arr= np.array([1,2,3,4,5,6,7])
print(arr)
print(type(arr))

# list lai chae array ma change gardinxa 
# ndarray= n dimenional array ma convert bhako 

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [1]:
import numpy as np 
arr=np.array((1,2,3,4,5))
# small bracket bhako chae tuple ho 
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [3]:
import numpy as np
arr= np.array(70)
# 70 bhaneko single number ho so it is 0-dimensional numpy array
print(arr)
type(arr.ndim)

70


int

In [4]:
# one dimensional array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [1]:
#two dimensional array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
# duita [[]] hune bitikae 2d array hunxa

print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(arr.ndim)
# ndim ley chae number o dimension dinxa 

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
