In [1]:
li=[2,3,4,5,6,7]
print(li)
type(li)


[2, 3, 4, 5, 6, 7]


list

In [6]:
import numpy as np 
arr= np.array([1,2,3,4,5,6,7])
print(arr)
print(type(arr))

# list lai chae array ma change gardinxa 
# ndarray= n dimenional array ma convert bhako 

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [1]:
import numpy as np 
arr=np.array((1,2,3,4,5))
# small bracket bhako chae tuple ho 
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [3]:
import numpy as np
arr= np.array(70)
# 70 bhaneko single number ho so it is 0-dimensional numpy array
print(arr)
type(arr.ndim)

70


int

In [4]:
# one dimensional array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [1]:
#two dimensional array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
# duita [[]] hune bitikae 2d array hunxa

print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [2]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]], ndmin=8)
print(arr)
print(arr.ndim)
# ndim ley chae number o dimension dinxa 

[[[[[[[[1 2 3]
       [4 5 6]
       [7 8 9]]]]]]]]
8


In [ ]:
# ndmin= is used to deine the number o dimensions the resulting array 


# size ley chae total number  elements dinxa 

# shape: it gives the size o array in each dimension 


# dtype= data type dinxa 

# nbytes= total number o array consumed by the array in memory

# T= transpose o array
 








In [ ]:
import numpy as np

array1 = np.array([[1,2,3],[6,7,8]])
print(array1.size)




6


In [ ]:
import numpy as np 
array1=np.array([[1,2,3],[6,7,8]])
print(array1.shape)
# 2*3 matrix ho bhaera dekhayo

(2, 3)


In [6]:
import numpy as np
array1=np.array([6,7.2,8.5])
# check the data type o array1 
print(array1.dtype)

float64


In [ ]:
import numpy as np
# created a deault 1-d array o integer
array1=np.array([6,7,8,9,10])

array2=np.array([6,7,8,10,13], dtype=np.int64)

print(array1.itemsize)
print(array2.itemsize)


8
8


In [2]:
import numpy as np
arr=np.zeros((3,5), dtype=np.float64)

# get total bytes consumed by the elements

total_bytes=arr.nbytes
print(f"Total bytes consumed by array elements: {total_bytes}")

# 15*8=120

Total bytes consumed by array elements: 120


In [ ]:
import numpy as np
# create  a 2d array
arr=np.array([[1,2,3],[4,5,6]])
print("original array:")
print(arr)


# transpose
transposed_arr=arr.T
print("transposeed array is")
print(transposed_arr)